### ISSUE TITLE
couchdb provider data

### ISSUE THREAD

**Issue by gabrielmancini** [oauth-io/oauthd#135]
Hi Guys,

   There is a way to replace redis with couchdb? i had this hoodie plugin https://github.com/goappes/hoodie-plugin-oauthio and i am wondering if i can setup the server inside my plugin, but to do this i will need change the redis calls to couchdb calls..

any north here?
cheers

**Comment by vados-xenon** [comment]
Closing as this is pretty old and the question was answered. Adding a DB Adapter to add some abstraction and extension points is something that we'll be working on, though CouchDB support is not currently planned (but should be possible to implement after other changes have been made).
