### ISSUE TITLE
Question about tricky provider configuration

### ISSUE THREAD

**Issue by pulkitsinghal** [oauth-io/oauthd#142]
I've forked-off a repo to add a new provider `Vend` which is a cloud based point-of-sale/cash-register for retailers.

But I'm finding it tricky to create a conf.json file because, based on the who is using their service, the url changes: `https://{domain_prefix}.vendhq.com` and I'm not sure how to accomodate that.

Would I use the `Parameters Object` for this? I'm imagining a pseudo-config like:

```
    "oauth2": {
        "authorize": {
            "url": "https://{domain_prefix}.vendhq.com/connect",
        },
        "parameters": {
            "domain_prefix": "string"
        }
    }
```

Is that correct?

**Comment by pulkitsinghal** [comment]
Any advice?

**Comment by pulkitsinghal** [comment]
I can pay up if that's what's needed here.

**Comment by bumpmann** [comment]
Hi, did you try with this config ? It should work with your custom field in parameters object

**Comment by pulkitsinghal** [comment]
@bumpmann - yes I tried my pseudo code ... the additional `domain_prefix` textfield that I try to configure for collecting user input never shows up in the UI and ultimately it fails with an error when attempting to save/configure/use it. Let me share `conf.json` it so that you may easily reproduce it.

```
{
  "name": "Vend",
  "desc": "Vend is point-of-sale, inventory, and customer loyalty software for iPad, Mac & PC. Easily manage and scale your business, from one store to many, in the cloud.",
  "url": "https://{domain_prefix}.vendhq.com/",
  "oauth2": {
    "oauth2": {
      "authorize": "https://{domain_prefix}.vendhq.com/connect",
      "access_token": "https://{domain_prefix}.vendhq.com/api/1.0/token",
      "refresh": "https://{domain_prefix}.vendhq.com/api/1.0/token",
      "parameters": {
        "client_id": "string",
        "client_secret": "string",
        "domain_prefix": "string"
      }
    }
  },
  "href": {
    "keys": "https://developers.vendhq.com/developer/applications/create",
    "docs": "https://developers.vendhq.com/documentation/oauth.html",
    "apps": "https://developers.vendhq.com/developer/applications",
    "provider": "https://developers.vendhq.com/"
  }
}
```

**Comment by pulkitsinghal** [comment]
@bumpmann - any tips?

**Comment by thyb** [comment]
Hi,

Sorry for the delay it tooks, I've digged into your issue,

As the {{domain_prefix}} is given in the authorization step, you can catch him using the `extra` field:

```json
{
	"name": "Vend",
	"desc": "Vend is point-of-sale, inventory, and customer loyalty software for iPad, Mac & PC. Easily manage and scale your business, from one store to many, in the cloud.",
	"url": "https://secure.vendhq.com/",
	"oauth2": {
		"authorize": {
			"url": "https://secure.vendhq.com/connect",
			"extra": [
				"domain_prefix"
			]
		},
		"access_token": "https://{{domain_prefix}}.vendhq.com/api/1.0/token",
		"refresh": "https://{{domain_prefix}}.vendhq.com/api/1.0/token",
		"parameters": {
			"client_id": "string",
			"client_secret": "string"
		}
	},
	"href": {
		"keys": "https://developers.vendhq.com/developer/applications/create",
		"docs": "https://developers.vendhq.com/documentation/oauth.html",
		"apps": "https://developers.vendhq.com/developer/applications",
		"provider": "https://developers.vendhq.com/"
	}
}
```

As you can see, you can specify extra parameters and reuse them in the other steps.

Vend has been released as a new OAuth provider in the version beta.9: https://github.com/oauth-io/oauthd/tree/1.0.0-beta.9
It has also been released in OAuth.io
