### ISSUE TITLE
500 error when open main page

### ISSUE THREAD

**Issue by Shaper2111** [oauth-io/oauthd#146]
After login I get a 500 (Internal Server Error) on all api links in console. But when i open, as example, api/plugins i've got this:
{"status":"error","code":404,"message":"/api/plugins does not exist","data":{"code":"ResourceNotFound"}}

**Comment by bumpmann** [comment]
I did not have this error for 1.0.0-rc.1, please reopen if you still see this error (btw, it's possible to use `debug:true` in config.js to have a better message / stack)
