### ISSUE TITLE
OAuthd do not save applications

### ISSUE THREAD

**Issue by valVk** [oauth-io/oauthd#147]
Every time I'm login all my applications goes away.

I've installed `"version": "1.0.0-beta.8",`
And also I have infinite loop to the `/api/apps`

I can get more information just ask me about

Thanks

**Comment by umbrella-alexander-khovansky** [comment]
I have this problem with the same version.
Actually it does save applications, it just cannot display their list since the call to /api/apps hangs. Created applications are available by their URLs.

**Comment by valVk** [comment]
yes, seems like it cant get list of application but they still accessible by their IDs

**Comment by poshetz** [comment]
+1 i have this same problem, i can save and see apps in redis but if i reload the page apps aren't shown, if i browse the url directly it shows the apps for example : 

     http://localhost:6284/apps/SOME_ID_HERE

**Comment by valVk** [comment]
@poshetz , how did you get the list of applications in redis?

**Comment by poshetz** [comment]
@valVk  just connecting to default port on localhost using rdm redis desktop manager, you'll see everything is there.... but not showing on client side...

**Comment by timic** [comment]
I have same bug with version 1.0.0-beta.17.

**Comment by poshetz** [comment]
@timic  tried beta16? Looks like it works

**Comment by shuriktm** [comment]
Will be this fixed?

I ran into the issue on 1.0.0-beta.17.

**Comment by develephant** [comment]
Still doesn't work in beta 16 or 17, I can create and list apps, but as soon as I delete one, no more list.

Anyone figured this out yet?

**Comment by develephant** [comment]
It appears the issue starts happening from beta 2 and up for what it's worth.

**Comment by valVk** [comment]
http://redisdesktop.com/ - this can help you to figure out how many application you have

**Comment by develephant** [comment]
Hi,

Thanks for the link, but that doesn't really solve the API problem. I would fix it myself if I knew the language better. You can see where things changed here. https://github.com/oauth-io/oauthd/compare/1.0.0-beta.1...1.0.0-beta.2?diff=split&name=1.0.0-beta.2

Cheers.

**Comment by thyb** [comment]
thanks @develephant for these informations. I think I now understand the issue (I wasn't able to reproduce it before). It seems your plugin oauthd-admin-auth is not up to date.
The change here: https://github.com/oauth-io/oauthd/commit/238c8c283851203135d10cb2b06533416fc146b4#diff-29dbfa25a44388fa86b2834fa14fd649L69 needs this commit in the oauthd-admin-auth plugin to work: https://github.com/oauth-io/oauthd-admin-auth/commit/5c6980f9e8dd6e0254170dc8c9f04b7562a12030
If you have not this commit, it explains why it's displaying an empty list.

`oauthd plugins update && grunt` should resolve the issue. The plugin oauthd-admin-auth should be in 0.1.3. Tell me if it works for you :)
