### ISSUE TITLE
How to use local oauthd daemon server on client side?

### ISSUE THREAD

**Issue by poshetz** [oauth-io/oauthd#149]
Hello, i installed the node daemon server locally, added a new app and providers, tryed oauth and it works.

It runs on http://localhost:6284/

Now i am wondering how do i use it on the client side as oauth server?
Do i need to specify the url of the local daemon somewhere in the code?

I would like to use my own server and not pay for an oauth.io account ,  so i am wondering if is this still possible?

thanks!!

**Comment by poshetz** [comment]
ok i think i found that, but i have another doubt, the code is this:

     OAuth.setOAuthdURL('http://localhost:6284')
        OAuth.initialize('NgQoxiHojc-dR6vLPqEoeyxzh1Y');
         OAuth.popup('facebook').then(function(facebook) {
         console.log(facebook);
         /*facebook.me().done(function(me) {

             console.log('Your name is ' + me.name)
          })*/
        });

Why i have to use an api key? i want to not call oauth.io in order to not pay and use my own server.

From the oauth.io dashboard i see all the calls i made to my own oauthd, is that normal? Will i pay for them?

thank you!!

**Comment by schaitanya** [comment]
You still need an API key even if you're hosting your oAuth service. But this key is generated from your server (not in oauth.io). So, No, you don't pay anything if you're hosting it yourself.

**Comment by poshetz** [comment]
thanks :+1:
