### ISSUE TITLE
Call the auth/provider/me from node ?

### ISSUE THREAD

**Issue by poshetz** [oauth-io/oauthd#151]
Sorry, how can i call the slashme urls  from node? Is it possible to retrieve user data by them?

**Comment by bumpmann** [comment]
Hi, this endpoint is documented at https://github.com/oauth-io/oauthd/wiki/API#user-data-api (see https://github.com/oauth-io/oauthd/wiki/API#requests-api for the http header).

If you're using the node sdk, you can also call the .me() method: https://github.com/oauth-io/sdk-node#basic-usage
