### ISSUE TITLE
Using OAuth.io in a Chrome Extension with jQuery

### ISSUE THREAD

**Issue by RichardLitt** [oauth-io/oauthd#152]
I am following off of #52. I've implemented everything requested in there, but I'm having trouble with this code:

```js
      OAuth.initialize('redacted_id')
      OAuth.popup('twitter', function (e, r) {
        // to use r.get etc. you need to have jquery included at this point
        r.get('/1.1/account/verify_credentials.json').done(function (data) {
          console.log('Data', data)
        })
      })
```

I can't get r.get to work, even though I have `var r = require('jquery')` at the top of the file and I am browserifying it. How do I include jQuery in my code? How do I get `r` to be defined?  

Putting it in the `<head>` of my HTML page I am using for my Chrome extension and allowing the jQuery cdn by adding the html to the `content_security_police` field doesn't work, either.

**Comment by bumpmann** [comment]
the get post put etc.. methods come from oauth-js, this bug is related to https://github.com/oauth-io/oauth-js/issues/63

**Comment by RichardLitt** [comment]
No longer getting this, since using code from https://github.com/oauth-io/oauth-js/issues/63. Closing this issue.
