### ISSUE TITLE
Best way to test a new provider?

### ISSUE THREAD

**Issue by brycereynolds** [oauth-io/oauthd#156]
I'm trying to add Edmodo as a provider but I'd like to test my settings prior to asking for a pull request. I tried creating my own instance but now realize that it uses providers that are officially supported - and not local to my instance. If there is a way to add a provider locally and see it in my oauthd instance that would also suffice.

Any advice?

**Comment by thyb** [comment]
If you're using your own instance, it's already using the local providers from the `providers/` folder: https://github.com/oauth-io/oauthd/tree/master/providers

After adding a new provider in this folder, don't forget to restart the oauthd instance to reload all provider's configuration file. If your provider, don't appear in the provider list, it's probably a parse error in the json file.
