### ISSUE TITLE
Add support for Jive and Chatter

### ISSUE THREAD

**Issue by dparlevliet** [oauth-io/oauthd#161]
Hi,

We were planning to use your service for our app soon, but we need Jive and Chatter in addition to some others which you already support. Is there a reason these two are not support or has it just not been necessary yet?

Jive: https://community.jivesoftware.com/docs/DOC-97348
Chatter: https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickstart_connecting.htm

**Comment by vados-xenon** [comment]
Closing this as those projects have been since acquired/are different and the requirements have probably shifted a lot for this.
