### ISSUE TITLE
Question: both client and server side usage

### ISSUE THREAD

**Issue by hotrush** [oauth-io/oauthd#166]
For example, if i authorize my app for users using client-side authorization, and then will use received credentials for any backend queued calls - will this cause any problems for me?

**Comment by thyb** [comment]
There is no real issue to use the access token in the frontend and then, to send it to the backend.
There is 2 benefits of using the server side flow only:
- The server side flow assure that the access token received in the backend is the good one (prevent spoofing)
- If you have an existing XSS/CSRF vulnerability in your frontend, the attacker wont be able to retrieve the access token of the user (as it doesn't go by the frontend). Using Angular.js or such framework help a lot to prevent this vulnerability.

**Comment by hotrush** [comment]
I have read your docs more properly and found next: http://docs.oauth.io/?PHP#authorizing-the-user-with-both-front-end-and-back-end-sdks
Think that is the best way for me.
Thanks for your help!
