### ISSUE TITLE
oauthd init not available

### ISSUE THREAD

**Issue by chandu-atina** [oauth-io/oauthd#167]
oauthd has only limited options. Tried "init" and "-v" options with oauthd command and found that they aren't available.

Machine : Ubuntu 14.04
NodeJS version : v0.10.37
npm version : 2.12.1

XXXX:~/softwares/oauthd$ oauthd -v
Usage: oauthd {status|config|start|stop|restart}

XXXX:~/softwares/oauthd$ oauthd init
Usage: oauthd {status|config|start|stop|restart}

**Comment by thyb** [comment]
It seems you have a really old version of oauthd.
Use `npm ls oauthd -g` to know your current version
The latest version is 1.0.0-beta.17

You can update oauthd using `sudo npm update oauthd -g`

Tell us if it works :)

**Comment by chandu-atina** [comment]
Thank you so much, updating oauthd solved the issue:)
