### ISSUE TITLE
Got "internalError" when using oauthd with Doorkeeper

### ISSUE THREAD

**Issue by henggana** [oauth-io/oauthd#168]
I got "internalError" message when trying oauthd with Rails based provider built using Doorkeeper

Internal error {
  "body": {
    "code": "InternalError"
  }
}

Other thing I noticed is Oauthd send request with 'response_type=code', eventhough I choose "client-side(token)" on oauth provider setting.

What cause the internal error ?
And why Oauthd not use "response_type=token" when using client-side response type setting ?

Thanks.

**Comment by thyb** [comment]
I'm not sure for Doorkeeper (I've never used it yet) but the response_type is normal, even if the provider allows 2-legged OAuth, we're doing it in 3-legged so the response_type don't change.
If I understand well for Doorkeeper, you try to use oauthd to ease the integration of your new OAuth provider. Can I see your configuration file of your provider?
You can try to add `debug: true` in the config.js file of your oauthd instance, it gives sometimes more information.

**Comment by henggana** [comment]
This is the configuration file:

```json
{
  "name": "[name]",
  "desc": "[desc]",
  "url": "https://[domain]/oauth",
  "oauth2": {
    "authorize": "/authorize",
    "access_token": "/token",
    "request": {
      "url": " https://[domain]/api/v1",
      "cors": false,
      "query": {
        "access_token": "{{token}}"
      },
      "headers": {
        "Accept": "application/json"
      }
    },
    "refresh": "/token",
    "parameters": {
      "client_secret": "string",
      "client_id": "string",
      "scope": {}
    }
  },
  "href": {
    "provider": "https://[domain]"
  }
}
```

FYI, it's use oauthd-legacy.

I tried to install it on my machine and connect it to local provider with same configuration (except url), It works, it return access_token, access_type, and expires_in. 

I looked into request log file, local provider have two request (1) to get auth code (2) get token with auth_code as parameter. But provider on production, only have request (1).

Thanks for your help.

**Comment by henggana** [comment]
I try to find where "InternalError" in oauthd comes from, it leads me to lib/formatters.js and body var value is `UNABLE_TO_VERIFY_LEAF_SIGNATURE`. Does it have something to do with SSL certificate ?

**Comment by schaitanya** [comment]
@henggana Yes, this is indeed for invalid SSL certs. I guess this because you're using your localhost ?
If thats the case you can set `NODE_TLS_REJECT_UNAUTHORIZED=0` to ignore it.

**Comment by henggana** [comment]
@schaitanya It's because of self-signed SSL cert :)

Thanks. Closing now.
