### ISSUE TITLE
oauthd daemon REST urls

### ISSUE THREAD

**Issue by 45kb** [oauth-io/oauthd#172]
Hi, i am using the oauthd daemon on a server to make calls through nodejs  (backend).

At the moment i am able to request user data/infos via the `/me` (slashme) url but i don't understand how to make REST POST and DELETE calls to post or delete user statuses/posts on the platforms.

Is it possible?
Is there any documentation about the daemon REST urls or a full list of them?

Thanks.

**Comment by thyb** [comment]
Hi, The list of endpoints is documented here: https://github.com/oauth-io/oauthd/wiki/API

For the Request Feature, go directly to this URL: https://github.com/oauth-io/oauthd/wiki/API#requests-api

**Comment by 45kb** [comment]
Thank you @thyb , i think now it's more clear, i will try it.

**Comment by 45kb** [comment]
Hi @thyb  sorry for disturbing, i have few questions if you can.

I am finally using request APIs both for facebook and twitter, everything works great, thanks for the awesome oauthd, simplifies so much.

Do you even know if it is possible to perform BATCH / Bulk requests with oauthd?

Thank you a lot.
