### ISSUE TITLE
Facebook's birthday field swaps "day" and "month"

### ISSUE THREAD

**Issue by rinoto** [oauth-io/oauthd#174]
The `birthday` field in Facebook is always retrieved in `MM/DD/YYYY` format. See [Facebook Graph API](https://developers.facebook.com/docs/graph-api/reference/user):

> The person's birthday. This is a fixed format string, like MM/DD/YYYY

But [Oauth.io facebook's me.js](https://github.com/oauth-io/oauthd/blob/master/providers/facebook/me.js#L36) assumes that the `day` is in the first position and the `month` in the second one.

```
            if (me.birthday) {
                var array = me.birthday.split('/');
                if (array) {
                    return {
                        day: array[0],
                        month: array[1],
                        year: array[2]
                    }
                }
            }

```
thanks,
Ruben

**Comment by thyb** [comment]
Thanks for the feedback, it has been fixed in https://github.com/oauth-io/oauthd/commit/8644f2b27b3f0cad6c3dd6d947e170d69e4b9ebd
