### ISSUE TITLE
Issues in getting access token using the providers refresh token

### ISSUE THREAD

**Issue by vinodjoseph91** [oauth-io/oauthd#178]
I have implemented a oauthd server side authentication using node.js sdk for provider 'Asana'. The first call where I get the access token and refresh token works fine and I am able to make rest api calls using the access token for 1 hour. Later I get an access token expired error. I am referring to this documentation to get new access token [http://docs.oauth.io/?Node#refreshing-the-tokens].
I have a credentials object which I pass along with session to this method as OAuth.refreshCredentials(credentials, req.session). I get a success response but the response content is same as the very first response which I get in making a authentication call ie the access token, expire time everything remains to be the same and rest api calls fail with the same error message.
What might be the problem .

Below is my code for authentication (POST call) , I have set the force_refesh to true.

`app.post('/oauth/signin', function(req, res) {
    var code = req.body.code;
    oauth.auth(provider, req.session, {
        code: code,
        force_refresh: true
    })
        .then(function(request_object) {
            credentials = request_object.getCredentials();
            res.send(200, request_object.access_token);
        })
        .fail(function(e) {
            res.send(400, 'Invalid code');
        });
});`

This is the credentials object which I save
credentials :{"access_token":"***","token_type":"bearer","expires_in":3600,"request":{"url":"***","headers":{"Authorization":"Bearer {{token}}"}},"refresh_token":"*****","state":"60e43-527-07-56-02b4a982","provider":"asana","expires":1461695678925}

This is the GET call for getting new access token using refresh token (should it be a POST instead) 

`app.get('/refresh', function(req, res) {
if(credentials && credentials.refresh_token){
oauth.refreshCredentials(credentials, req.session)
    .then(function(newOAuthResult) {
        res.json(newOAuthResult);
    })
    .fail(function(e) {
        console.log('Error :'+e);
        res.send(400,'refresh failed');
    });
    }
    else{
    	res.send(401,'Unauthorized');
    }
});`

This is the response object which is same as the first response without new access token

After refresh :{"access_token":"*****","token_type":"bearer","expires_in":3600,"request":{"url":"****","headers":{"Authorization":"Bearer {{token}}"}},"refresh_token":"*****","state":"ecsd43e-46c-ec-528-fa351","provider":"asana","expires":1461693874176,"refreshed":false}

Should I do any settings in my asana application, or is it happening because of any coding mistake.
Or should I have to use the javascript rest api as mentioned here [http://docs.oauth.io/?Javascript#refreshing-the-tokens](url) to get new access token like this

https://oauth.io/auth/refresh_token/:provider
Body:  token: REFRESH_TOKEN  key: PUBLIC_OAUTHIO_KEY  secret: SECRET_OAUTHIO_KEY

or is it that we can't get refreshed access tokens using Oauthd server.

- Can I make a refresh access token call before the access token gets expired ?

Any help would be appreciated.

**Comment by vinodjoseph62** [comment]
With the recent asana refresh api being added. This issue seems to be fixed.
