### ISSUE TITLE
When facebook or google return no gender: gender is set to 1

### ISSUE THREAD

**Issue by dran1337** [oauth-io/oauthd#188]
When there is no gender value returned by facebook or google the oauth.io gender is set to 1 (female).

See https://github.com/oauth-io/oauthd/blob/master/providers/facebook/me.js (line 19)

```
 gender: function(me) {
            return me.gender == 'male' ? 0 : 1;
        },
```

See https://github.com/oauth-io/oauthd/blob/master/providers/google_plus/me.js (line 25)

```
   gender: function(me) {
            return me.gender == 'male' ? 0 : 1;
        },
```

This may also apply  for other providers

**Comment by thyb** [comment]
Thanks for the feedback, it has been fixed in our latest release 1.0.0-rc.1 in https://github.com/oauth-io/oauthd/commit/9b6dc5dd90bf5e6f3ace76a7aa9550e809cc1f85

We'll propagate the new oauthd version in OAuth.io within a week
