### ISSUE TITLE
DNS issues when connecting to redis

### ISSUE THREAD

**Issue by deepakprabhakara** [oauth-io/oauthd#190]
We are having some trouble with oauthd and redis. If the redis server dns changes (pods moving around in Kubernetes for example) then looks like outhd is unable to reconnect to the new IP. Are dns lookups to redis cached by any chance?

**Comment by bumpmann** [comment]
Hi, we changed node-redis for ioredis in 1.0.0-rc.1. Please tell me if it fixes this issue on your side

**Comment by deepakprabhakara** [comment]
Great news, thanks. I'll let you know if the issue still exists with the upgrade.
