### ISSUE TITLE
Are there any plans to update the npm modules? They seem quite outdated, especially resitfy.

### ISSUE THREAD

**Issue by deepakprabhakara** [oauth-io/oauthd#192]
There also seem to be security advisories against 'Regular Expression Denial of Service' - [https://nodesecurity.io/advisories/106](https://nodesecurity.io/advisories/106)

**Comment by thyb** [comment]
Unfortunately, upgrading Restify implies lots of modification in OAuthd.
We've started few weeks ago a global rewrite of OAuthd which include :

* Moving from Restify to Express & Upgrade to Node 6
* Moving from Coffeescript to Typescript
* Moving from Redis to PostgreSQL
* New UX

This new version should be available hopefully in December.

**Comment by deepakprabhakara** [comment]
Thanks @thyb . That sounds great. It would be excellent if the db layer can be made pluggable. We'd love to use MongoDB instead of Redis or PostgreSQL.

**Comment by thyb** [comment]
MongoDB is unfortunately not in the plan.

To be totally transparent, we've released [Materia](https://getmateria.com) in September: It's a software to develop a full backend visually. It's totally extensible thanks addons and currently support MySQL, PostgreSQL and SQLite (so it would be really easy within oauthd to switch from MySQL to PostgreSQL).
Under the wood, Materia uses the latest version of Express, Node.js and Sequelize (Node.js SQL ORM to handle several SQL databases). Sequelize doesn't support MongoDB as it's not a relational database.

This will bring lots of advantage to oauthd compared to the current settings:
- Choice in SQL databases
- Modularity through Materia addons (OAuth addon / Usermanagement addon / OAuth Server Addon etc..)
- A nice interface to really know what's going on in the database
- The ability to connect your production oauthd instance directly within Materia Designer
- The ability (for us) to add some proprietary addons for OAuth.io (e.g. analytics / payments etc..)
- Easily configurable through JSON configuration files
- Delivered as a Docker container - easy to deploy anywhere

Some features like addons are not yet fully implemented in Materia yet but it's on the [roadmap](https://github.com/webshell/materia-designer/projects/2).

- Addons (https://github.com/webshell/materia-designer/issues/59) and Live connection to the production database (https://github.com/webshell/materia-designer/issues/23) should be releases in the October release (in few weeks)
- Docker container is already available but a nice deployment solution using flynn.io will be released hopefully for the November release

**Comment by thyb** [comment]
We've decided to upgrade OAuth.io & oauthd step by step to not rebuild everything from scratch to iterate faster.

We've just released the version **1.0.0-rc.1**

This new version upgrade all dependencies of oauthd including Restify, node 7 and a migration to ioredis which is more maintained with a compatible API than node-redis. It also fixes some old issues and add a bunch of providers (cf: https://github.com/oauth-io/oauthd/commit/9b6dc5dd90bf5e6f3ace76a7aa9550e809cc1f85)

To update, you can run `(sudo) npm update -g oauthd`

In your existing instances, you need to edit `plugins.json` to update the version of the plugins by replacing `0.x.x` by `1.x.x` and then, you can run `oauthd plugins install` to update all plugins to the latest version.

**Comment by deepakprabhakara** [comment]
Great news, thanks.
