### ISSUE TITLE
Oauthd updates

### ISSUE THREAD

**Issue by vinodjoseph62** [oauth-io/oauthd#193]
After the recent changes in oauthd, If we update the old oauthd server base with the newer one , will things work as usual. Will the old  oauth client_Id and client_secret remain the same. Or should we setup a new instance of it.  I just wanted to retain my old clientId and secret.

**Comment by thyb** [comment]
Sure, it has been developed with this use case in mind. We've used it on OAuth.io and it worked fine :)

To update, you can run `(sudo) npm update -g oauthd`

In your existing instances, you need to edit `plugins.json` to update the version of the plugins by replacing `0.x.x` by `1.x.x` and then, you can run `oauthd plugins install` to update all plugins to the latest version.

**Comment by vinodjoseph62** [comment]
Cool, will check that, thanks.

**Comment by srinisubramanian** [comment]
We tried that .. oauthd updated .. 
however when we run the command oauthd plugins install in the instance folder the error displayed is "An error occured: Object.values is not a function" (we are running node 6.9.2)

**Comment by thyb** [comment]
Following this link: http://stackoverflow.com/questions/40421825/how-to-use-object-values-on-server-side-in-node-js

>Object.values is a new feature in ES2017. It is very bleeding edge. Node.js has full support for it from version 7.0.
>
>6.8.1 supports it, but it is considered unstable and is locked behind the --harmony flag.
> You can either:
> * Upgrade to the latest Node.js LTS and use --harmony
> * Upgrade to the latest Node.js Current
> * Use a polyfill

**Comment by thyb** [comment]
I've just commit this fix which resolve your issue: https://github.com/oauth-io/oauthd/commit/e173ed80f8e6194d9f5b7adcc1d52264476d52db

Tested on Node v5.3.0 ; It will be available in oauthd v1.0.2
