### ISSUE TITLE
XSS Vulnerability in Firefox

### ISSUE THREAD

**Issue by cv711** [oauth-io/oauthd#194]
Hi there,

arbitrary Javascript code can be injected as part of the `redirect_uri=` query parameter and that's fine for most browsers because they block it natively. Unfortunately, in **Firefox** when attempting to print an error message for whatever reason it executes the injected code. That might also apply for other query parameters too.

e.g. `.../auth/google?redirect_uri=%3Cimg%20src=a%20onerror=prompt(document.cookie)%3E`

Thanks,
Chris

**Comment by thyb** [comment]
Thanks a lot for the feedback, we're taking a look at it.

**Comment by thyb** [comment]
@bumpmann fixed the vulnerability in this commit: https://github.com/oauth-io/oauthd/commit/4c3e4e5cc85279c5011f4f7254b2806247ed7182

Thanks again 👍

**Comment by thyb** [comment]
It has just been published in 1.0.2
