### ISSUE TITLE
Slack Issues for "incoming webhooks"

### ISSUE THREAD

**Issue by arashb31** [oauth-io/oauthd#198]
When using oAuth.io to set up an incoming-webhook with Slack, the channel information is not included as part of the data that is proxied via oAuth.io

Slack returns a "incoming_webhook" property as part of their response that has the channel information (including webhook URL), however, oauth.io isn't passing this back.

The snippet from (from Slack documentation at https://api.slack.com/incoming-webhooks) is below:

![2017-04-11 19_34_51-incoming webhooks _ slack](https://cloud.githubusercontent.com/assets/1490000/24935140/fc38cb50-1eed-11e7-9166-e246af032a01.png)

**Comment by thyb** [comment]
Thanks for the report,

I haven't tested yet but it should works by changing https://github.com/oauth-io/oauthd/blob/master/providers/slack/conf.json#L7 by:

```javascript
"access_token": {
   "url": "/api/oauth.access",
   "extra": [
      "team_name",
      "incoming_webhook"
   ]
}
```

Like we've done with Salesforce here: https://github.com/oauth-io/oauthd/blob/master/providers/salesforce/conf.json#L9

I'm going to try it tomorrow and merge it in OAuth.io if it works :)

**Comment by arashb31** [comment]
Great to hear thanks

**Comment by arashb31** [comment]
I believe "bot" should also be added as a property in the "extra" array, as per Slack docs on this page:
https://api.slack.com/docs/slack-button

**Comment by arashb31** [comment]
Also, when you request "identity.team" scope, the response includes a "team" property, which I believe should also be added to the "extra" array, as it includes the team name (which isn't included part of the oAuth.io .me() call)

https://api.slack.com/methods/users.identity

**Comment by thyb** [comment]
Thanks for the added information, take a look at this commit: https://github.com/oauth-io/oauthd/commit/b41431d4d608f7cad819a42d7f8a9267c85ff163

I ended up with these extra fields:
```json
"extra": [
    "team_name",
    "team_id",
    "team",
    "user",
    "incoming_webhook",
    "bot"
]
```

I have also updated all the scopes which were incomplete.
I think it's okay now. I'll deploy this commit on OAuth.io shortly.

**Comment by arashb31** [comment]
There seems to be an issues with me() calls now.

<img width="757" alt="screenshot 2017-04-17 11 12 32" src="https://cloud.githubusercontent.com/assets/1490000/25093182/1193b08a-235f-11e7-8a5a-73c838d42b54.png">

**Comment by arashb31** [comment]
Any update on this?

**Comment by sepandb** [comment]
Hi there,

I am having the same issue with Slack when I try to get the incoming-webhook data. The only thing that gets returned from Oauth.io is the "access_token" and "scope". I'm doing this using the oAuth.io service. How come the "extra"s mentioned above aren't included?
Thanks,
