### ISSUE TITLE
Still supported / active?

### ISSUE THREAD

**Issue by youradds** [oauth-io/oauthd#206]
Is this project still going, or has it died? My admin area just comes up with a "5" now, and even after rebooting I still can't get into the admin area. Just not sure if its worth posting my question here, as nothing seems to get answered any more :/

**Comment by vados-xenon** [comment]
Closing this issue -- I've been brought on to give the code base a little bit of TLC as the F/OSS side has atrophied a bit.

Sorry for the bug @youradds, please re-open this if you still have this issue @youradds  (assuming you're still using `oauthd` at all)
