### ISSUE TITLE
XSS Vulnerability with upper cased Javascript protocol

### ISSUE THREAD

**Issue by cv711** [oauth-io/oauthd#209]
Hi,

we found that arbitrary Javascript code can be injected as part of the `redirect_uri=` query parameter if its value begins like this `Javascript: ...`. Lower cased version of `javascript` is blocked but not this one.

e.g. `.../auth/google?redirect_uri=Javascript:alert(document.cookie)//`

Thanks,
Chris

**Comment by cv711** [comment]
It's actually coming from the `url` module. If replaced with the `url-parse` module that is more actively maintained urls are parsed correctly and it goes away.

**Comment by vados-xenon** [comment]
Closing as neither `url` nor `url-parse` seem to be in use anymore. Will re-open if this is still an issue.
