### ISSUE TITLE
This is a dead project.. right???

### ISSUE THREAD

**Issue by xewonder** [oauth-io/oauthd#259]
anyone following up on this or is it just dead??

**Comment by youradds** [comment]
Feels like it :( Does anyone know of another project that does the same thing? I'm moving servers and I know I had a bugger of a job getting it all moved over last time around. Thinking I may as well jump ship if it's not being supported any more

**Comment by vados-xenon** [comment]
Closing this issue -- I've been brought on to give the code base a little bit of TLC as the F/OSS side has atrophied a bit.
