### ISSUE TITLE
The service is offline

### ISSUE THREAD

**Issue by alexweinstein** [oauth-io/oauthd#260]
Service stopped working this morning. I am a paying customer. Please fix.

**Comment by vados-xenon** [comment]
Hey @alexweinstein I'm working on giving this project a bit of love/development, can you confirm that service was restored?

**Comment by alexweinstein** [comment]
> Hey @alexweinstein I'm working on giving this project a bit of love/development, can you confirm that service was restored?

That would be amazing. Thank you for doing this. 

Yes. The service was restored. It was down for 2 days straight. Since then there have been two instances of downtime: April 19 (5 hours) and May 18 (8 hours). I can send you more detailed reports if it would help.

**Comment by vados-xenon** [comment]
> Yes. The service was restored. It was down for 2 days straight. Since then there have been two instances of downtime: April 19 (5 hours) and May 18 (8 hours). I can send you more detailed reports if it would help.

Thank you! I was involved in fixing that last one, really hoping to get some more 9s in there. I appreciate you reporting it and giving such detailed information -- I may reach out in the future, if you don't mind to get your help/cooperation on some things we're doing internally.

**Comment by alexweinstein** [comment]
@vados-xenon Please do. Happy to help however I can. Thank you!

**Comment by vados-xenon** [comment]
Hey @alexweinstein just want to confirm that you've seen no disruption of service -- a report was filed that there was a temporary loss of service for the API -- would you mind emailing us at support@oauth.io ?

**Comment by alexweinstein** [comment]
@vados-xenon sending an email now.

**Comment by vados-xenon** [comment]
Thanks! As soon as I get it I'll expand on what the report/etc :bow:
