### ISSUE TITLE
Using OAuth.io within a Chrome Extension

### ISSUE THREAD

**Issue by athieriot** [oauth-io/oauthd#52]
Hi,

I am currently trying to use `OAuth.io` (Using the _Stackoverflow_ provider) into a `Chrome Extension`. Note:
- It is a [BrowserAction](http://developer.chrome.com/extensions/browserAction.html) type extension. And the place where I try to get authorisation from the user is the _Popup_ page.
- I am using `OAuth.io` with the standard oauth.js library via the popup method.

It almost go through the entire process but, unfortunately, the window can't send back the token to the opener.
Therefore, the callback in the Javascript code is never called and it's impossible to make further API calls.

I am afraid that there will be no other possibility than using, one way or another, the specific methods provided by Google to send message across windows/tabs. As suggested and documented here:
- http://stackoverflow.com/questions/11812786/window-open-returns-undefined-in-chrome-extension
- http://developer.chrome.com/extensions/messaging.html

And I am under the impression that this kind of modifications will require commit into `oauthd` as well as `oauth-js`.

Can you tell me if there is already existing solutions to avoid this issue? And if not, do you think it would be reasonable work to provide a specific solution in order to develop a Chrome Extension?

Thank you.

Aurélien

**Comment by DomiR** [comment]
Hey, I have a followup question. I'm also trying to use this in a chrome extension, calling te Oauth.popup method from the extensions popup. But I'm getting a {message: "The popup was closed"} error, even though I see "successfully access granted" after clicking a grant button in the loginpopup. It waits for a second, then closes the popup automatically, then I see the error. 
* Using the newest version.  
* "externally_connectable" :{"matches": ["https://oauth.io/*"]}
* also in permissions

Are there other reasons this could throw the error wrongfully?
Thanks

**Comment by RichardLitt** [comment]
I'm also having an issue. I'm not seeing anything in the popup, at all; a window pop ups and closes itself without displaying any text inside of it. My console says that r.get isn't working, even though I have jQuery loaded. in the `<head>` as well. Is there something I am missing?

**Comment by RichardLitt** [comment]
No longer getting this issue, as of: https://github.com/oauth-io/oauth-js/issues/63.
