### ISSUE TITLE
Error: Origin "http://localhost" does not match any registered domain/url

### ISSUE THREAD

**Issue by ne0c0de** [oauth-io/oauthd#99]
Hi,

I setup OAuthd on a dedicated server and changed oauthio.com domains to that server domain on my mobile app (that's developed with PhoneGap (Cordova)).

When i try to login with Twitter it gives me that error:

Error: Origin "http://localhost" does not match any registered domain/url on oath.xxx.com

What should i need to do?

**Comment by ne0c0de** [comment]
Hi all,

Time is going fast, i was resolve the problem by keeping localhost in the domains. 

But twitter recently changed their security policies and wants to get exact callback url should be defined in the app settings.

So i defined localhost on it but it's not accepting it. Does anyone know what should be the exact callback url?

**Comment by vados-xenon** [comment]
Closing as this is pretty old and it looks like the problem was resolved at least partially, please re-open if this is still an issue (assuming you're still using `oauthd`).
